bedrock_agentcore:
  agent_id: null
  agent_arn: null
  agent_name: vuln_collector_agent
  entrypoint: runtime_app.py
  execution_role: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/service-role/<EXECUTION_ROLE_NAME>"
  platform: linux/arm64
  runtime_type: PYTHON_3_13
  s3_path: "s3://<SOURCE_BUCKET_NAME>"
  network_mode: PUBLIC

codebuild:
  enabled: true

memory: 2048

observability:
  enabled: true